
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        # 기본 페이지 사이즈
        default-page-size: 10
        # 최대 페이지 사이즈
        max-page-size: 2000
#        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
  # sql문에 쿼리 파라미터 보여주는거
#  org.hibernate.type: trace